import { Language } from './types';

export const translations: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    appName: 'RightWay Travel',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Login to your account to continue',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'Enter your 10-digit number',
    sendOtp: 'Send OTP',
    loginWithGoogle: 'Login with Google',
    otpTitle: 'OTP Verification',
    otpSubtitle: 'Enter the OTP sent to',
    verifyOtp: 'Verify OTP',
    resendOtp: 'Resend OTP',
    homeTitle: 'Book Your Next Trip',
    homeSubtitle: 'Select a service to get started',
    hotel: 'Hotel',
    bus: 'Bus',
    train: 'Train',
    flight: 'Flight',
    metro: 'Metro',
    navHome: 'Home',
    navBookings: 'Bookings',
    navProfile: 'Profile',
    searchTitle: 'Find Your Perfect {category}',
    from: 'From',
    to: 'To',
    date: 'Date',
    guests: 'Guests',
    search: 'Search',
    searchResults: 'Search Results',
    bookNow: 'Book Now',
    bookingSummary: 'Booking Summary',
    yourDetails: 'Your Details',
    fullName: 'Full Name',
    age: 'Age',
    email: 'Email Address',
    proceedToPayment: 'Proceed to Payment',
    profileTitle: 'My Profile',
    editProfile: 'Edit Profile',
    savedBookings: 'Saved Bookings',
    logout: 'Logout',
    useCurrentLocation: 'Use Current Location',
    fetchingLocation: 'Fetching location...',
    locationPermissionDenied: 'Location permission was denied. Please check your browser settings.',
    locationUnavailable: 'Location is unavailable.',
    searchLocationPlaceholder: 'Search city, station, or airport...',
    recentLocations: 'Recent Locations',
  },
  [Language.TA]: {
    appName: 'ரைட்வே டிராவல்',
    loginTitle: 'மீண்டும் வரவேற்கிறோம்',
    loginSubtitle: 'தொடர உங்கள் கணக்கில் உள்நுழையவும்',
    phoneLabel: 'தொலைபேசி எண்',
    phonePlaceholder: 'உங்கள் 10 இலக்க எண்ணை உள்ளிடவும்',
    sendOtp: 'OTP அனுப்பு',
    loginWithGoogle: 'Google மூலம் உள்நுழையவும்',
    otpTitle: 'OTP சரிபார்ப்பு',
    otpSubtitle: 'அனுப்பப்பட்ட OTP ஐ உள்ளிடவும்',
    verifyOtp: 'OTP ஐ சரிபார்க்கவும்',
    resendOtp: 'மீண்டும் OTP அனுப்பு',
    homeTitle: 'உங்கள் அடுத்த பயணத்தை பதிவு செய்யுங்கள்',
    homeSubtitle: 'தொடங்குவதற்கு ஒரு சேவையைத் தேர்ந்தெடுக்கவும்',
    hotel: 'ஹோட்டல்',
    bus: 'பேருந்து',
    train: 'ரயில்',
    flight: 'விமானம்',
    metro: 'மெட்ரோ',
    navHome: 'முகப்பு',
    navBookings: 'பதிவுகள்',
    navProfile: 'சுயவிவரம்',
    searchTitle: 'உங்கள் சரியான {category} ஐக் கண்டறியவும்',
    from: 'இங்கிருந்து',
    to: 'இங்கு',
    date: 'தேதி',
    guests: 'விருந்தினர்கள்',
    search: 'தேடு',
    searchResults: 'தேடல் முடிவுகள்',
    bookNow: 'இப்போதே பதிவு செய்',
    bookingSummary: 'பதிவு சுருக்கம்',
    yourDetails: 'உங்கள் விவரங்கள்',
    fullName: 'முழு பெயர்',
    age: 'வயது',
    email: 'மின்னஞ்சல் முகவரி',
    proceedToPayment: 'பணம் செலுத்த தொடரவும்',
    profileTitle: 'எனது சுயவிவரம்',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    savedBookings: 'சேமித்த பதிவுகள்',
    logout: 'வெளியேறு',
    useCurrentLocation: 'தற்போதைய இடத்தை பயன்படுத்தவும்',
    fetchingLocation: 'இருப்பிடத்தைப் பெறுகிறது...',
    locationPermissionDenied: 'இருப்பிட அனுமதி மறுக்கப்பட்டது. உங்கள் உலாவி அமைப்புகளைச் சரிபார்க்கவும்.',
    locationUnavailable: 'இருப்பிடம் கிடைக்கவில்லை.',
    searchLocationPlaceholder: 'நகரம், நிலையம் அல்லது விமான நிலையத்தைத் தேடுங்கள்...',
    recentLocations: 'சமீபத்திய இடங்கள்',
  },
};

export const MOCK_LOCATIONS = [
    'Mumbai, India',
    'Delhi, India',
    'Bengaluru, India',
    'Chennai, Tamil Nadu',
    'Kolkata, India',
    'Hyderabad, India',
    'Pune, India',
    'Ahmedabad, India',
    'Jaipur, India',
    'Madurai, Tamil Nadu',
    'Coimbatore, Tamil Nadu',
    'Tiruchirappalli, Tamil Nadu',
];

export const RECENT_LOCATIONS = [
    'Chennai, Tamil Nadu',
    'Bengaluru, India',
];